### ISSUE TITLE
No Support for the until operator

### ISSUE THREAD

**Issue by RandallShanePhD** [ryanmcgrath/twython#329]
It looks like the until operator is not recognized.  If I search for dog using until, the following is returned in the search metadata['refersh_url'] which makes the until operator appear as part of the query string.

u'?since_id=469075417995821057&q=dog%20until%3A2014-05-21&result_type=mixed&include_entities=1',

I am looking at it now - happy to contribute the fix to this great library!!

**Comment by b-chow** [comment]
https://dev.twitter.com/rest/public/search

In the Twitter API docs, examples show that the  "until:" operator (along with similar operators like "from:" and "since:") should be included as part of the query string.

https://api.twitter.com/1.1/search/tweets.json?q=from%3ACmdr_Hadfield%20%23nasa&result_type=popular

The above is an example from the API docs that shows how to use "from:", which I think is the same format as the "until:" operator.

Hope this helps you guys out!
