### ISSUE TITLE
Full Text

### ISSUE THREAD

**Issue by standarddev** [ryanmcgrath/twython#495]
How would I add the tweet_mode='extended' within this package?

**Comment by RedactedCode** [comment]
Quite straightforward.
example:
    twitter.get_user_timeline(screen_name='somename', tweet_mode='extended')

the documentation is at [](https://twython.readthedocs.io/en/latest/index.html)

**Comment by 10poundbaby** [comment]
Am I putting this in the right portion of my code?

```
import cups
from twython import TwythonStreamer

#set up the printer
conn = cups.Connection()
printers = conn.getPrinters()
prin = conn.getDefault()

from auth import (
    consumer_key,
    consumer_secret,
    access_token,
    access_token_secret
)

class MyStreamer(TwythonStreamer):
    def on_success(self, data):
        if 'text' in data:
            username = data['user']['screen_name']
            tweet = data['text']

            #Creates a text file and writes the tweet to that file
            fout = open ("twitter.txt","w")
            fout.write("@{}:\n".format(username))
            fout.write("{}".format(tweet))
            fout.close()

            #Prints the text file
            conn.printFile(prin, "/home/pi/twitter.txt"," ", {})
      
stream = MyStreamer(
    consumer_key,
    consumer_secret,
    access_token,
    access_token_secret
    )

stream.statuses.filter(track='#overheard', tweet_mode='extended')
```
It still cuts off at 140 characters.

**Comment by RedactedCode** [comment]
You need to look at the actual payload that the stream delivers: the top-level key 'text' only contains the first 140 chars.
In most (but not all) status payloads there is also a top-level key 'extended_tweet' containing the subkey 'full_text' which has 280-char tweet content.
In order to - I think - to cater for legacy applications which haven't been updated to allow for 280-char tweets, some payloads don't have an 'extended_tweet' key, but you'll need to get onto the Twitter devs forum  to confirm.
You can't so far as I can tell distinguish in advance which payloads have extended tweets and which don't , so you'll have to use some conditionals using get() or similar.
This doesn't seem to me to be a Twython problem so much as your not really understanding the payload structure fully.
You'll also need to look into whether the "tweet_mode=extended" parameter works on the streaming endpoint.
good luck
